dataset:
  name: "becos"
  train_folder: "BeCoS/full_full/train/"
  val_folder: "BeCoS/partial_full/val/"
  pattern: None
rendering:
  partial_views: 4
  partial_views_full: 9
  num_partial_shapes: 2
options:
  save_model_name: "becos"
