dataset:
  name: "faust"
  train_folder: "FAUST_r/off/"
  val_folder: "FAUST_r/"
  pattern: None
rendering:
  partial_views: 1
  partial_views_full: 4
  num_partial_shapes: 1
options:
  save_model_name: "faust_debug"
